theme: jekyll-theme-hacker
title: Project Satori 
description: Will be linking with TheGlobalBitcoin.com so others can add subdomains such as Japan.TheGlobalBitcoin.com Europe.TheGlobalBitcoin.Com or Australia.TheGlobalBitcoin.Com
